### ISSUE TITLE
Segmentation fault on Mac

### ISSUE THREAD

**Issue by mbkumar** [zhanghe9704/tpsa#12]
The code compiles fine with clang++ on Mac with M2 Pro chip and Ventura OS. However the resulting executable crashes with a segmentation fault. Since a lot of researchers use Mac, fixing this would lead to wider adoption of the code.

**Comment by zhanghe9704** [comment]
Would you please be more specific about what happened on Mac? 

I install clang on Ubuntu 20.04. It compiles and the executable runs as normal.

If you were running the tests, it is known a segmentation fault will happen when all the tests pass (as written on the readme). I have spent many hours trying to find the reason and I believe it's the way how CATCH2 handles the memory. TPSA will create a memory pool for all the DA calculations. I have tested a very simple case, in which only three base vectors are created and no calculations are carried out. Inside CATCH2, I can see when the tests are done and the destructors of the base vectors are called, the values of the pointers to the base vectors were changed. The destructor of a DA vector will reset the value of all the elements to zero. A segmentation fault could happen when trying to set values at the wrong addresses. I don't know why this happens because I can't figure out what CATCH2 has done. But this does not happen outside CATCH2. TPSA has a function called da_clear(), which manually releases the memory pool. Calling this function in CATCH2 always causes a segmentation fault. Neither does this happen outside CATCH2. To make things worse or better, it only happens on Linux. On Windows, no segmentation fault with CATCH2.  I feel it's kind of outside my capability to solve this problem. And to speak frankly, I also don't think it is necessary to solve it because I believe it's not a problem of the TPSA code. 

If a normal executable crashes with a segmentation fault on Mac, that's an issue. Unfortunately, I have never used a Mac OS and have no access to any of them now. I probably can't work on it right now.

**Comment by mbkumar** [comment]
I think it is exhibiting behavior similar to the one seen on Linux then. Yes, the segfault is  happening with the example.
