### ISSUE TITLE
[JOSS Review] Documentation - Installation instructions

### ISSUE THREAD

**Issue by CFGrote** [zhanghe9704/tpsa#5]
https://github.com/openjournals/joss-reviews/issues/4818

The installation instructions in the README are fine but the cmake file (CMakeLists.txt) does not specify any dependencies beyondthe minimal cmake version. As observed in #2 , there are e.g. limitations on the gcc-version (gcc<=10 ok, gcc-12 fails). 

Also, the tests depend on Catch2 and it remains unclear if that framework is included with the sources or needs to be installed separately.

- [x] Clearly list all dependencies in the README
- [ ] ~Put checks for  dependencies and build enviroment (e.g. gcc version) into CMakeLists.txt~
- [ ] ~Add third party libraries (e.g. Catch2) as additional build targets into cmake (use [cmake's ExternalProject](https://cmake.org/cmake/help/latest/module/ExternalProject.html#module:ExternalProject)).~

I'll be happy to assist with the cmake edits.

**Comment by zhanghe9704** [comment]
Catch2 was a header-only library when this code was submitted to JOSS. The
header file is included in the tests folder.
(Catch2 has changed a lot since then. Not header-only anymore.) The C++
library should not depend on anything else.
The Python version depends on Python and Pybind11. In the updated
repository, which combined the original two repos
into one, Python and Pybind11 are checked in the CMake file. However, users
could install the Python library using PIP
insteadnof cmake.

Thanks and regards,
He

**Comment by CFGrote** [comment]
Looks good.
